name:                haskell-parse-stlc
version:             0.1.0.0
github:              "garbaz/haskell-parse-stlc"
license:             BSD3
author:              "Garbaz"
maintainer:          "garbaze@t-online.de"
copyright:           "2022 Garbaz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/garbaz/haskell-parse-stlc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-parse-stlc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-parse-stlc

tests:
  haskell-parse-stlc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-parse-stlc
